- name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist  # <--- Certifique-se de que isso existe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
